spring:
  application:
    name: greenkawsay-backend
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Lima

server:
  port: 8081
  servlet:
    context-path: /api

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Spring Boot Actuator Configuration for Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  level:
    com.greenkawsay: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE